name: Cleanup Old Packages
on:
  schedule:
    - cron: '0 0 * * 0' # Runs weekly on Sundays
  workflow_dispatch: # Allows manual triggering

jobs:
  delete-older-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@v5
        with:
          # Use your custom secret PAT with delete:packages permissions
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          package-name: 'your-package-name'
          package-type: 'container'
          min-versions-to-keep: 5
